sonar.projectKey=ec-healthcare
sonar.projectName=ec-healthcare
sonar.projectVersion=1.4
sonar.host.url=https://aw-sonar.singsys.net
sonar.login=singsys
sonar.password=Singsys@123
sonar.sources=.
sonar.language=php
sonar.sourceEncoding=UTF-8
sonar.exclusions=composer.json,package.json,public/**, config/**, database/**, vendor/**, test/**, storage/**, bootstrap/**


# command to run sonar
# sonar-scanner -Dsonar.projectKey=ec-healthcare -Dsonar.sources=. -Dsonar.host.url=https://aw-sonar.singsys.net -Dsonar.login=singsys -Dsonar.passwor=Singsys@123 